print ("This is \\\\ double backslash")
print ("This is /\\/\\/\\/\\/\\ mountain")
print ("He is\tawesome")
print ("\\\" \\n \\t \\\'")
#            Or
print (r"This is \\ double backslash")
print (r"This is /\/\/\/\/\ mountain")
print ("He is\tawesome")
print (r"\" \n \t \'")
print("\U0001F600	")